name: Debug with SSH

on:
  workflow_dispatch:   # 手动触发

jobs:
  debug:
    runs-on: ubuntu-latest
    timeout-minutes: 360   # 最长 6 小时
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Start SSH session with tmate
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false   # 只允许触发者访问，提升安全性