name: Check CF IPs via Proxy

on:
  schedule:
    - cron: "0 0 * * *"   # 每天运行一次
  workflow_dispatch:       # 手动触发


jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install aiohttp

      - name: Set proxy
        run: |
          echo "http_proxy=http://f2O9Sw2sqd:zbZEBEqbho@onepro.v6.mohic.lol:58433" >> $GITHUB_ENV
          echo "https_proxy=http://f2O9Sw2sqd:zbZEBEqbho@onepro.v6.mohic.lol:58433" >> $GITHUB_ENV
          echo "no_proxy=http://f2O9Sw2sqd:zbZEBEqbho@onepro.v6.mohic.lol:58433" >> $GITHUB_ENV

      - name: Run CF check script
        run: python cf_check.py

      - name: Commit results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add blocked.txt unblocked.txt
          git commit -m "Update CF IP lists via proxy"
          git push